-- ADD ALL ADDRESSES
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('12345 holling rd', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('275 KENT ST', 'SYDNEY', 'NSW', 2000);

-- ADD ALL USER DATA WITH ADDRESS SEQ NO IN ADDRESSID
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (1232854, 1, 'MR', 'test', 'tsetlast', 'MALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (1234556, 2, 'MR', 'FN1', 'LN1', 'MALE');