-- ADD ALL ADDRESSES
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('12345 holling rd', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('275 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('9280 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('9150 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('5690 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('4861 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('3812 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('6228 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('660 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('2165 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('9741 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('9567 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('8237 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('3430 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('9225 KENT ST', 'SYDNEY', 'NSW', 2000);
INSERT INTO ADDRESS  (STREET, CITY, STATE, POSTCODE) VALUES ('4550 KENT ST', 'SYDNEY', 'NSW', 2000);

-- ADD ALL USER DATA WITH ADDRESS SEQ NO IN ADDRESSID
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (1232854, 1, 'MR', 'test', 'tsetlast', 'MALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (1234556, 2, 'MR', 'FN1', 'LN1', 'MALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (588636421, 3, 'MR', 'FN2', 'LN2', 'MALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (881504505, 5, 'MR', 'FN3', 'LN3', 'MALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (502390812, 6, 'MR', 'FN4', 'LN4', 'FEMALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (683474520, 7, 'MR', 'FN5', 'LN5', 'MALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (655268186, 8, 'MR', 'FN6', 'LN6', 'MALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (608591793, 9, 'MR', 'FN7', 'LN7', 'FEMALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (847792233, 10, 'MR', 'FN8', 'LN8', 'MALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (203351020, 11, 'MR', 'FN9', 'LN9', 'MALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (34168551, 12, 'MR', 'FN10', 'LN10', 'FEMALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (536835439, 13, 'MR', 'FN11', 'LN11', 'MALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (1051251700, 14, 'MR', 'FN12', 'LN12', 'FEMALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (990155538, 15, 'MR', 'FN13', 'LN13', 'MALE');
INSERT INTO USERS (EMPID, ADDRESSID, TITLE, FIRSTNAME, LASTNAME, GENDER) VALUES (341699250, 16, 'MR', 'FN14', 'LN14', 'FEMALE');