
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE ADDRESS (

ID BIGINT AUTO_INCREMENT PRIMARY KEY,
STREET VARCHAR(50) NOT NULL,
CITY VARCHAR(20) NOT NULL,
STATE VARCHAR (20) NOT NULL,
POSTCODE INT NOT NULL,
CREATEDDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USERS (

EMPID BIGINT PRIMARY KEY,
ADDRESSID BIGINT,
TITLE VARCHAR(20) NOT NULL,
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
GENDER VARCHAR(20) NOT NULL,
CREATEDDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
UPDATEDDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT FK_USERS_ADDRESS FOREIGN KEY (ADDRESSID) REFERENCES ADDRESS(ID) ON DELETE CASCADE
);